---

- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
           systemd
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
           systemd
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-aget.service
     enabled: yes
     state: started
