---

- hosts: all
  become: yes
  tasks:
  -  name: Install postfix on Ubuntu
     apt:
        name=postfix
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:


  -  name: Install dovecot-core on Ubuntu
     apt:
        name=dovecot-core
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:

  -  name: Install dovecot-imapd on Ubuntu
     apt:
        name=dovecot-imapd
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:

  -  name: Install dovecot-pop3d on Ubuntu
     apt:
        name=dovecot-pop3d
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:

  -  name: Install dovecot-lmtpd on Ubuntu
     apt:
        name=dovecot-lmtpd
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:

  -  name: Install roundcube on Ubuntu
     apt:
        name=roundcube
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:

